# This is a basic workflow to help you get started with Actions

name: Hadoop CI Job

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  build:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v2
    
      # Setup JDK       
      - uses: actions/setup-java@v2
        with:
          java-version: '8'
          distribution: 'adopt'  
          
      - name: Cache local Maven repository
        uses: actions/cache@v2
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-
                    
      # Runs a set of commands using the runners shell
      - name: Multiple linux commands
        run: |
          java -version
          mvn -version      
          
      # Build maven project and generate jar
      - name: Build project with maven
        run: mvn clean install

      - uses: actions/upload-artifact@v2
        with:
          name: upload mapreduce jar
          path: /home/runner/work/hadoop-template/hadoop-template/target/Hadoop-template-1.0.jar
          
      - name: executing remote ssh commands using ssh key
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.SSH_HOST }}
          username: shubhamkarnwal08
          key: ${{ secrets.KEY_ED25519 }}
          port: 22
          script: sh hello.sh

      
